CREATE TABLE IF NOT EXISTS BorgerUser ( 
  id INTEGER PRIMARY KEY, 
  UserId INTEGER NOT NULL UNIQUE,  
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE IF NOT EXISTS Address (
  Id INTEGER PRIMARY KEY, 
  BorgerUserId INTEGER NOT NULL, 
  Address TEXT NOT NULL, C
  reatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, 
  IsValid BOOLEAN DEFAULT 1, 
  FOREIGN KEY(BorgerUserId) 
  REFERENCES BorgerUser(UserId) 
  ON DELETE CASCADE
);