CREATE TABLE IF NOT EXISTS SkatUser (
  id INTEGER PRIMARY KEY, 
  UserId INTEGER NOT NULL, 
  CreatedAt DEFAULT CURRENT_TIMESTAMP, 
  IsActive BOOLEAN DEFAULT 1 
);

CREATE TABLE IF NOT EXISTS SkatYear (
  id INTEGER PRIMARY KEY,
  Label TEXT NOT NULL,
  CreatedAt DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ModifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  StartDate DATETIME NOT NULL,
  EndDate DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS SkatUserYear (
  id INTEGER PRIMARY KEY,
  SkatUserId INTEGER NOT NULL,
  SkatYearId INTEGER NOT NULL,
  UserId INTEGER NOT NULL,
  IsPaid BOOLEAN DEFAULT 0,
  Amount INTEGER NOT NULL,
  FOREIGN KEY(SkatUserId) REFERENCES SkatUser(id),
  FOREIGN KEY(SkatYearId) REFERENCES SkatYear(id)
);